name: gallery
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-334.3.beta

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^14.6.1
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
      - asset: assets/fonts/Poppins/Poppins-Black.ttf
      - asset: assets/fonts/Poppins/Poppins-Bold.ttf
      - asset: assets/fonts/Poppins/Poppins-Italic.ttf
        style: italic
      - asset: assets/fonts/Poppins/Poppins-Medium.ttf
    
    - family: Trirong
      fonts:
      - asset: assets/fonts/Poppins/Trirong-Bold.ttf

   